- src/commands/godbolt.rs
Adding a `\n` at the end of the `note` would, when the message gets truncated, separate the note itself and the 'Output too large. Godbolt link: ...' message. And, in the case the note would happen to be at the end of the message, Discord trims trailing newlines.
I'm pretty sure this should work but haven't actually tested it.
> `?godbolt` - add missing line break

- src/commands/utilities.rs
Problem: when using `/selftimeout`, if you *only* specify the duration in hours, then an unexpected extra hour is added to the time.
Result: pain and suffering. I have to wait an extra hour before ~~being offtopic in general~~ participating in productive conversations.
Solution: match on the `hours` value when minutes isn't specified. If it's `0`, then the current default (60) is still used. If it's nonzero, use 0 instead.
> Fix /selftimeout parameter handling

- src/commands/playground/util.rs
Currently, Ferris attempts to edit the reply after the timeout of 600 seconds. However, if Ferris' response has been deleted, this will cause an Unknown Message error. To fix this, errors from editing the message will be ignored.
> fix: ignore Unknown Message error

- Cargo.lock
- Cargo.toml
- src/checks.rs
- src/commands/crates.rs
- src/commands/godbolt.rs
- src/commands/godbolt/targets.rs
- src/commands/modmail.rs
- src/commands/playground/util.rs
- src/commands/utilities.rs
- src/helpers.rs
- src/main.rs
- src/types.rs
(...and bump other dependencies)
Closes #17. Necessary for #8. Will supersede #20 if merged.
Please note that I haven't tested that it actually works.
> Update to serenity 0.12

- src/main.rs
The missing code block error now uses code blocks to nicely format the error message:
> Missing code block error now uses code blocks itself

- src/commands/modmail.rs
If you forgot to give the bot access to the modmail channel you entered in `Secrets.toml`, the error message wouldn't help you to figure out what went wrong.
Previous error that was inscrutable:
> 024-01-09T14:32:02.131-05:00 [Runtime]  WARN chaitrex_ferrisbot_test: Encountered error: Setup { error: Missing Access
New error message:
> 2024-01-09T14:28:38.710-05:00 [Runtime]  WARN chaitrex_ferrisbot_test: Encountered error: Setup { error: Cannot enter modmail channel, …
> Improved error message when bot can't enter modmail channel

- Cargo.lock
- Cargo.toml
- src/commands/playground/misc_commands.rs
- src/commands/playground/play_eval.rs
- src/commands/playground/util.rs
- src/main.rs
i have made `maybe_wrap` work properly, instead of just doing string substitutions.
> fixes `)};{(` and other fun

- Cargo.lock
- src/commands/playground/misc_commands.rs
- src/commands/playground/play_eval.rs
- src/commands/playground/util.rs
- src/main.rs
so while discord renders emojis `<a:$emoji_id>` just fine poises matcher thing does not, and therefore I sort of broke the emoji based commands.
> fix #27 breaking emojis

- src/main.rs
As recently discussed in #rustbot-development.
Closes #26.
> Disallow mentions by default

- src/commands/playground/util.rs
- src/main.rs
I did not test this locally. I attempted to revert it as cleanly as possible.
If you prefer I can also revert the *entire* change which has a higher chance of being correct.
fixes #29
> Revert the formatting part of the syn wrap change

- src/commands/playground/api.rs
- src/commands/playground/util.rs
Playground now supports 2024 edition in dropdown. This PR enables the bot to use 2024 edition.
Example here:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=ec174b3bb8eb2b158e857379fdec9e0c
I think I got everything, but let me know if more needs to be done.
> Allow edition 2024 on playground

- src/commands/godbolt.rs
- src/commands/modmail.rs
- src/commands/playground/api.rs
- src/commands/playground/misc_commands.rs
- src/commands/playground/play_eval.rs
- src/commands/playground/util.rs
- src/main.rs
This fixes the godbolt command as godbolt has never officially supported passing `--color`. Instead of stripping the ANSI sequences as previously done, we can now just use discord's ANSI codeblock rendering.
> Use godbolt's colour output via ANSI codeblocks

- src/commands/playground/misc_commands.rs
- src/commands/playground/play_eval.rs
- src/commands/playground/util.rs
> fixes the pretty printing that `:ferrisCat: eval` should cause

- src/commands/godbolt.rs
> enhance godbolt further

- src/commands/godbolt.rs
- src/commands/godbolt/targets.rs
- src/commands/playground/procmacro.rs
- src/commands/playground/util.rs
- src/main.rs
Since 2024 edition was just released, we can now default to it.
I believe I got everything, but please do a double check just to make sure. Let me know if there are any other thoughts.
Also, one note that as of this current comment date, godbolt has not _yet_ upgraded to 1.85 (I'm sure they will soon), so technically godbolt will be broken for a short time if this is merged before they update
> Default to 2024 edition

- src/commands/utilities.rs
Idk how discord bots work but I imagine this fixes the command reply stuff. I took inspiration from the `/crate` or `?crate` commands, which also uses `ctx.send()` and I know works as expected.
> Get a better response

- src/commands/godbolt.rs
What the title says, im not sure if `#[inline(never)]` should be mentioned or if its too long
> Added checking for `#[unsafe(no_mangle)]` and `#[inline(never)]` in the ?godbolt command

- src/commands.rs
- src/commands/man.rs
- src/main.rs
Closes #13.
I initially planned to implement pagination and man page traversal using the `tuff-parser` crate while parsing the man files located at `/usr/share/man/`. However, I found it unnecessary since opening a website is significantly faster than scrolling through a paginated man page.
Screenshots:
Copilot Summary:
This pull request introduces a new `man` command to the project, which allows users to fetch and display man pages from the Debian website. The changes involve adding a new module, defining the command, and integrating it into the main command list.
New `man` command integration:
* [`src/commands.rs`](diffhunk://#diff-b86d43fce6a9c57160aa925719550d40a6ed3f5e5a0117679905f76e68acc520R6): Added a new module `man` to the list of public modules.
* …
> Add `/man` command (similar to crate and docs)

- Cargo.lock
- Cargo.toml
- src/commands/modmail.rs
- src/commands/thread_pin.rs
- src/commands/utilities.rs
- src/main.rs
Most notably replaces rusttype with ab_glyph to follow imageproc.
I did not do any testing, but it seems like there weren't any extreme API changes.
> chore: update dependencies

- Cargo.lock
- Cargo.toml
- src/commands/crates.rs
- src/commands/crates/tests.rs
When given a qualified path for the ?doc command, test the item kind by brute forcing each possible path concurrently through a HEAD request. A fast path first tests the "usual" variants based on the snake/pascal/screaming-snake case of the identifier, then fallback to other less likely types upon failure. A 2xx response from the documentation server is considered a positive response.
When multiple items with the same name (e.g. trait + derive macro) are present, whichever gets returned depends on luck (whichever the server responds more quickly and gets picked up by `FuturesUnordered`).
This can be controlled by writing `?doc trait@bevy::prelude::Component` instead.
Falls back to the old `?search=` response when the item cannot be found. This is especially useful for non-inline …
> Attempt to resolve an exact link for ?doc items

- Cargo.toml
- src/commands/godbolt.rs
previously it just used `x86asm` by default all the time, which sucked for arm
> highlight `--emit=mir` and `--emit=llvmir` sort of things properly

- Cargo.lock
- src/commands/godbolt.rs
- src/commands/man.rs
- src/commands/playground/microbench.rs
- src/commands/playground/util.rs
Poise doesn't allow keys to contain special characters without enclosing them in quotes, so this changes `aliasing_model` to be camelCased (also makes it much easier to use on mobile!). I tested this locally, so it should work now.
I also fixed Clippy in separate commits. The `format_push_string` lint is a bit contentious since it requires handling an error that should never occur. I fixed that in a separate commit, so if you'd prefer not doing that I can revert the commit and disable that lint.
> Fix: Miri Tree Borrows aliasingModel camel cased and appease clippy

- Cargo.lock
- Cargo.toml
- build.rs
- src/commands/crates.rs
- src/commands/godbolt.rs
- src/commands/godbolt/targets.rs
- src/commands/man.rs
- src/commands/modmail.rs
- src/commands/playground/api.rs
- src/commands/playground/microbench.rs
- src/commands/playground/misc_commands.rs
- src/commands/playground/play_eval.rs
- src/commands/playground/procmacro.rs
- src/commands/playground/util.rs
- src/commands/utilities.rs
- src/main.rs
- src/types.rs
This does three different maintenance tasks: fix clippy warnings, update to edition 2024 (which involves the new style edition), and update/reorganize/remove unnecessary dependencies. Each commit does one of these things. This _could_ be split up between multiple PRs, but I think these are fairly uncontroversial changes.
> maintenance: fix clippy warnings, update edition, reorganize/remove dependencies
